-- WHEN COMMITTING OR REVIEWING THIS FILE: Make sure that the timestamp in the file name (that serves as a version) is the latest timestamp, and that no new migration have been added in the meanwhile.
-- Adding migrations out of order may cause this migration to never execute or behave in an unexpected way.
-- Migrations should NOT BE EDITED. Add a new migration to apply changes.
-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------
drop Materialized view if exists dashboard.vw_historical_data
CREATE TABLE dashboard.historical_data_persistent_data (
                                                           id uuid PRIMARY KEY,
                                                           periodid uuid,
                                                           startdate date,
                                                           enddate date,
                                                           orderableid uuid,
                                                           facilityid uuid,
                                                           province text,
                                                           district text,
                                                           facilitytype text,
                                                           facilitycode text,
                                                           facilityname text,
                                                           productcode text,
                                                           productname text,
                                                           initialstock integer,
                                                           consumptions integer,
                                                           entries integer,
                                                           adjustments integer,
                                                           closestock integer,
                                                           requisitiononperiod text,
                                                           cmm numeric,
                                                           mos numeric,
                                                           approvedquantity bigint,
                                                           requestedquantity bigint,
                                                           expiredquantity bigint,
                                                           provincefacilitycode text,
                                                           districtfacilitycode text,
                                                           periodtype text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX if not exists historical_data_persistent_data_pkey ON dashboard.historical_data_persistent_data(id uuid_ops);
